DATA_FILE_PATH = 'data.json'
DEFAULT_COLOR = [0, 0, 0]
FONT_FILE = 'Inconsolata-Bold.ttf'
TEXT_ORIGIN = [50, 10]
DEFAULT_FONT_SIZE = 100
BACKGROUND_FOLDER = 'background'
BACKGROUND_KEY = '__bg__'
TEXT_KEY = 'txt'
SIZE_KEY = 'size'
COLOR_KEY = 'color'
OUTPUT_FOLDER = 'output'
